/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controller.Controladora;
import Dominio.Deportista;
import Dominio.Ejercicio;
import Dominio.Entrenador;
import Dominio.Especialidad;
import Dominio.Gimnasio;
import Dominio.Persona;
import Persistencia.PersonaXml;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.applet.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author LAB_A611
 */
public class VentanaPrincipal extends javax.swing.JFrame {
   
   Gimnasio regPersona = new  Gimnasio();
   Persona x;
   Controladora control;
   private boolean resultado = false;
   PersonaXml datos = new PersonaXml();
   ArrayList<Especialidad> aux = new ArrayList<Especialidad>();
   ArrayList<Ejercicio> aux1 = new ArrayList<Ejercicio>();
   
    
    public VentanaPrincipal() {
        initComponents();
        control = new Controladora(this);
        control.IniciarCursor(this);
        control.IniciarMusica();
        control.IniciarVentana(this,"../Imagenes/IconoGYM.png");      
        control.LlenarTabla(datos, TablaE, TablaD, txtExpE, null, null, null);
        control.activar_desactivarD(false, GuardarD);
        control.activar_desactivarE(false, GuardarE);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JLayeredPane();
        panelEntrenador = new javax.swing.JPanel();
        txtNombreE = new javax.swing.JTextField();
        txtEdadE = new javax.swing.JTextField();
        txtAlturaE = new javax.swing.JTextField();
        txtPesoE = new javax.swing.JTextField();
        txtExpE = new javax.swing.JTextField();
        RegistrarE = new javax.swing.JButton();
        boxSexoE = new javax.swing.JComboBox();
        IMCE = new javax.swing.JButton();
        txtCelE = new javax.swing.JTextField();
        ListaEsp = new javax.swing.JButton();
        txtEsp = new javax.swing.JTextField();
        txtHoras = new javax.swing.JTextField();
        GuardarE = new javax.swing.JButton();
        panelDeportista = new javax.swing.JPanel();
        txtNombreD = new javax.swing.JTextField();
        txtEdadD = new javax.swing.JTextField();
        txtAlturaD = new javax.swing.JTextField();
        txtPesoD = new javax.swing.JTextField();
        txtRitCarD = new javax.swing.JTextField();
        RegistrarD = new javax.swing.JButton();
        boxSexoD = new javax.swing.JComboBox();
        txtFrecEntrD = new javax.swing.JTextField();
        txtTipoEjerD = new javax.swing.JTextField();
        IMCD = new javax.swing.JButton();
        txtCelD = new javax.swing.JTextField();
        RutinaD = new javax.swing.JButton();
        txtEjer = new javax.swing.JTextField();
        RegistrarEjer = new javax.swing.JButton();
        txtObj = new javax.swing.JTextField();
        GuardarD = new javax.swing.JButton();
        panelConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaE = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaD = new javax.swing.JTable();
        panelUtilidades = new javax.swing.JPanel();
        eliminarP = new javax.swing.JButton();
        txtCelel = new javax.swing.JTextField();
        modificarE = new javax.swing.JButton();
        mostrarEsp = new javax.swing.JButton();
        mostrarEjer = new javax.swing.JButton();
        ejerFav = new javax.swing.JButton();
        modificarD = new javax.swing.JButton();
        PanelBotton = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        botonDeportista = new javax.swing.JButton();
        botonConsulta = new javax.swing.JButton();
        botonEntrenador = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelLogo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Platinum-Gold GYM");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelCentral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCentral.setLayout(new java.awt.CardLayout());

        txtNombreE.setText("Nombre:");
        txtNombreE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreEFocusLost(evt);
            }
        });
        txtNombreE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEKeyTyped(evt);
            }
        });

        txtEdadE.setText("Edad:");
        txtEdadE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEdadEFocusLost(evt);
            }
        });
        txtEdadE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadEKeyTyped(evt);
            }
        });

        txtAlturaE.setText("Altura:");
        txtAlturaE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAlturaEFocusLost(evt);
            }
        });
        txtAlturaE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlturaEKeyTyped(evt);
            }
        });

        txtPesoE.setText("Peso:");
        txtPesoE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesoEFocusLost(evt);
            }
        });
        txtPesoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoEKeyTyped(evt);
            }
        });

        txtExpE.setText("Años de experiencia laboral:");
        txtExpE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtExpEFocusLost(evt);
            }
        });
        txtExpE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExpEKeyTyped(evt);
            }
        });

        RegistrarE.setBackground(new java.awt.Color(153, 255, 153));
        RegistrarE.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        RegistrarE.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        RegistrarE.setText("Registrar");
        RegistrarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegistrarE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        RegistrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEActionPerformed(evt);
            }
        });

        boxSexoE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));

        IMCE.setBackground(new java.awt.Color(153, 255, 153));
        IMCE.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        IMCE.setForeground(new java.awt.Color(255, 255, 255));
        IMCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        IMCE.setText("IMC y PGC");
        IMCE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IMCE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        IMCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMCEActionPerformed(evt);
            }
        });

        txtCelE.setText("Cedula:");
        txtCelE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelEFocusLost(evt);
            }
        });
        txtCelE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelEKeyTyped(evt);
            }
        });

        ListaEsp.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        ListaEsp.setForeground(new java.awt.Color(255, 255, 255));
        ListaEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        ListaEsp.setText("Registrar especialidad");
        ListaEsp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ListaEsp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        ListaEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaEspActionPerformed(evt);
            }
        });

        txtEsp.setText("Especialidad:");
        txtEsp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEspFocusLost(evt);
            }
        });
        txtEsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEspKeyTyped(evt);
            }
        });

        txtHoras.setText("Horas dictadas:");
        txtHoras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHorasFocusLost(evt);
            }
        });
        txtHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHorasKeyTyped(evt);
            }
        });

        GuardarE.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        GuardarE.setForeground(new java.awt.Color(255, 255, 255));
        GuardarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        GuardarE.setText("Guardar cambios");
        GuardarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GuardarE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        GuardarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEntrenadorLayout = new javax.swing.GroupLayout(panelEntrenador);
        panelEntrenador.setLayout(panelEntrenadorLayout);
        panelEntrenadorLayout.setHorizontalGroup(
            panelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntrenadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCelE, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreE)
                    .addComponent(txtEdadE)
                    .addComponent(txtAlturaE)
                    .addComponent(txtPesoE)
                    .addComponent(txtExpE)
                    .addGroup(panelEntrenadorLayout.createSequentialGroup()
                        .addComponent(boxSexoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntrenadorLayout.createSequentialGroup()
                        .addGroup(panelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHoras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(txtEsp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEntrenadorLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RegistrarE, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IMCE, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GuardarE, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(ListaEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelEntrenadorLayout.setVerticalGroup(
            panelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntrenadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCelE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEdadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxSexoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAlturaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtExpE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEntrenadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEntrenadorLayout.createSequentialGroup()
                        .addComponent(txtEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ListaEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(IMCE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegistrarE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GuardarE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        panelCentral.add(panelEntrenador, "card2");

        txtNombreD.setText("Nombre:");
        txtNombreD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreDFocusLost(evt);
            }
        });
        txtNombreD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreDKeyTyped(evt);
            }
        });

        txtEdadD.setText("Edad:");
        txtEdadD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEdadDFocusLost(evt);
            }
        });
        txtEdadD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadDKeyTyped(evt);
            }
        });

        txtAlturaD.setText("Altura:");
        txtAlturaD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAlturaDFocusLost(evt);
            }
        });
        txtAlturaD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlturaDKeyTyped(evt);
            }
        });

        txtPesoD.setText("Peso:");
        txtPesoD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesoDFocusLost(evt);
            }
        });
        txtPesoD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoDKeyTyped(evt);
            }
        });

        txtRitCarD.setText("Ritmo Cardiaco:");
        txtRitCarD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRitCarDFocusLost(evt);
            }
        });
        txtRitCarD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRitCarDKeyTyped(evt);
            }
        });

        RegistrarD.setBackground(new java.awt.Color(153, 255, 153));
        RegistrarD.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        RegistrarD.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        RegistrarD.setText("Registrar");
        RegistrarD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegistrarD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        RegistrarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarDActionPerformed(evt);
            }
        });

        boxSexoD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));

        txtFrecEntrD.setText("Frecuencia de entrenamiento:");
        txtFrecEntrD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFrecEntrDFocusLost(evt);
            }
        });
        txtFrecEntrD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrecEntrDKeyTyped(evt);
            }
        });

        txtTipoEjerD.setText("Tipo de ejercicios:");
        txtTipoEjerD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoEjerDFocusLost(evt);
            }
        });
        txtTipoEjerD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipoEjerDKeyTyped(evt);
            }
        });

        IMCD.setBackground(new java.awt.Color(153, 255, 153));
        IMCD.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        IMCD.setForeground(new java.awt.Color(255, 255, 255));
        IMCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        IMCD.setText("IMC y PGC");
        IMCD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IMCD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        IMCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMCDActionPerformed(evt);
            }
        });

        txtCelD.setText("Cedula:");
        txtCelD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelDFocusLost(evt);
            }
        });
        txtCelD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelDKeyTyped(evt);
            }
        });

        RutinaD.setBackground(new java.awt.Color(153, 255, 153));
        RutinaD.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        RutinaD.setForeground(new java.awt.Color(255, 255, 255));
        RutinaD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        RutinaD.setText("Determinar rutina");
        RutinaD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RutinaD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        RutinaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutinaDActionPerformed(evt);
            }
        });

        txtEjer.setText("Nombre del ejercicio:");
        txtEjer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEjerFocusLost(evt);
            }
        });
        txtEjer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEjerKeyTyped(evt);
            }
        });

        RegistrarEjer.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        RegistrarEjer.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarEjer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        RegistrarEjer.setText("Registrar ejercicio");
        RegistrarEjer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegistrarEjer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        RegistrarEjer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEjerActionPerformed(evt);
            }
        });

        txtObj.setText("Objetivo del ejercicio:");
        txtObj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObjFocusLost(evt);
            }
        });
        txtObj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObjKeyTyped(evt);
            }
        });

        GuardarD.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        GuardarD.setForeground(new java.awt.Color(255, 255, 255));
        GuardarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        GuardarD.setText("Guardar cambios");
        GuardarD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GuardarD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        GuardarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeportistaLayout = new javax.swing.GroupLayout(panelDeportista);
        panelDeportista.setLayout(panelDeportistaLayout);
        panelDeportistaLayout.setHorizontalGroup(
            panelDeportistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeportistaLayout.createSequentialGroup()
                .addGroup(panelDeportistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeportistaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDeportistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFrecEntrD, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEdadD)
                            .addComponent(txtAlturaD)
                            .addComponent(txtPesoD)
                            .addComponent(txtRitCarD)
                            .addComponent(txtTipoEjerD)
                            .addComponent(txtNombreD)
                            .addComponent(txtCelD)
                            .addGroup(panelDeportistaLayout.createSequentialGroup()
                                .addComponent(boxSexoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 366, Short.MAX_VALUE))
                            .addGroup(panelDeportistaLayout.createSequentialGroup()
                                .addGroup(panelDeportistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEjer)
                                    .addComponent(txtObj))
                                .addGap(18, 18, 18)
                                .addComponent(RegistrarEjer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDeportistaLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(panelDeportistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegistrarD, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardarD, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RutinaD, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IMCD, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDeportistaLayout.setVerticalGroup(
            panelDeportistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeportistaLayout.createSequentialGroup()
                .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtCelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEdadD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxSexoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlturaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRitCarD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFrecEntrD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoEjerD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDeportistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDeportistaLayout.createSequentialGroup()
                        .addComponent(txtEjer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtObj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RegistrarEjer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IMCD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RutinaD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegistrarD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GuardarD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelCentral.add(panelDeportista, "card3");

        TablaE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cedula", "Edad", "Sexo", "Peso", "Altura", "Años de experiencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaE);

        TablaD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cedula", "Edad", "Sexo", "Peso", "Altura", "Ritmo Cardiaco", "Frecuencia de entrenamiento", "Tipo de ejercicios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaD);

        javax.swing.GroupLayout panelConsultaLayout = new javax.swing.GroupLayout(panelConsulta);
        panelConsulta.setLayout(panelConsultaLayout);
        panelConsultaLayout.setHorizontalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );
        panelConsultaLayout.setVerticalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCentral.add(panelConsulta, "card4");

        eliminarP.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        eliminarP.setForeground(new java.awt.Color(255, 255, 255));
        eliminarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        eliminarP.setText("Eliminar Persona");
        eliminarP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarP.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        eliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPActionPerformed(evt);
            }
        });

        txtCelel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCelel.setText("Buscar cedula:");
        txtCelel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelelFocusLost(evt);
            }
        });
        txtCelel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelelKeyTyped(evt);
            }
        });

        modificarE.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        modificarE.setForeground(new java.awt.Color(255, 255, 255));
        modificarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        modificarE.setText("Modificar Entrenador");
        modificarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modificarE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        modificarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEActionPerformed(evt);
            }
        });

        mostrarEsp.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        mostrarEsp.setForeground(new java.awt.Color(255, 255, 255));
        mostrarEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        mostrarEsp.setText("Mostrar especialidades");
        mostrarEsp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mostrarEsp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        mostrarEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEspActionPerformed(evt);
            }
        });

        mostrarEjer.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        mostrarEjer.setForeground(new java.awt.Color(255, 255, 255));
        mostrarEjer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        mostrarEjer.setText("Mostrar ejercicios");
        mostrarEjer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mostrarEjer.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        mostrarEjer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEjerActionPerformed(evt);
            }
        });

        ejerFav.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        ejerFav.setForeground(new java.awt.Color(255, 255, 255));
        ejerFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        ejerFav.setText("Ejercicio favorito");
        ejerFav.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ejerFav.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        ejerFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejerFavActionPerformed(evt);
            }
        });

        modificarD.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        modificarD.setForeground(new java.awt.Color(255, 255, 255));
        modificarD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        modificarD.setText("Modificar Deportista");
        modificarD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modificarD.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        modificarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUtilidadesLayout = new javax.swing.GroupLayout(panelUtilidades);
        panelUtilidades.setLayout(panelUtilidadesLayout);
        panelUtilidadesLayout.setHorizontalGroup(
            panelUtilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtilidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCelel)
                .addContainerGap())
            .addGroup(panelUtilidadesLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(panelUtilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ejerFav, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUtilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mostrarEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modificarE, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(eliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(mostrarEjer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(modificarD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        panelUtilidadesLayout.setVerticalGroup(
            panelUtilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtilidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCelel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modificarE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modificarD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mostrarEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mostrarEjer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ejerFav, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        panelCentral.add(panelUtilidades, "card5");

        botonSalir.setBackground(new java.awt.Color(153, 255, 153));
        botonSalir.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSalirMouseClicked(evt);
            }
        });

        botonDeportista.setBackground(new java.awt.Color(153, 255, 153));
        botonDeportista.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        botonDeportista.setForeground(new java.awt.Color(255, 255, 255));
        botonDeportista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        botonDeportista.setText("Registrar deportista");
        botonDeportista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDeportista.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        botonDeportista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeportistaActionPerformed(evt);
            }
        });

        botonConsulta.setBackground(new java.awt.Color(153, 255, 153));
        botonConsulta.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        botonConsulta.setForeground(new java.awt.Color(255, 255, 255));
        botonConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        botonConsulta.setText("Consultar datos");
        botonConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonConsulta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        botonConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultaActionPerformed(evt);
            }
        });

        botonEntrenador.setBackground(new java.awt.Color(153, 255, 153));
        botonEntrenador.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        botonEntrenador.setForeground(new java.awt.Color(255, 255, 255));
        botonEntrenador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        botonEntrenador.setText("Registrar entrenador");
        botonEntrenador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEntrenador.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        botonEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrenadorActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton1.png"))); // NOI18N
        jButton1.setText("Utilidades");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBottonLayout = new javax.swing.GroupLayout(PanelBotton);
        PanelBotton.setLayout(PanelBottonLayout);
        PanelBottonLayout.setHorizontalGroup(
            PanelBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBottonLayout.createSequentialGroup()
                .addGroup(PanelBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBottonLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PanelBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(botonEntrenador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonDeportista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelBottonLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBottonLayout.setVerticalGroup(
            PanelBottonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBottonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonDeportista, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Platinum-Gold GYM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N

        javax.swing.GroupLayout PanelLogoLayout = new javax.swing.GroupLayout(PanelLogo);
        PanelLogo.setLayout(PanelLogoLayout);
        PanelLogoLayout.setHorizontalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        PanelLogoLayout.setVerticalGroup(
            PanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(panelCentral))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelBotton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelCentral))
                .addGap(11, 11, 11))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrenadorActionPerformed
        control.activarPanel(panelEntrenador, panelDeportista, panelConsulta, panelUtilidades);
    }//GEN-LAST:event_botonEntrenadorActionPerformed

    private void botonConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultaActionPerformed
        control.activarPanel(panelConsulta, panelEntrenador, panelDeportista, panelUtilidades);
        TablaE.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {}, new String [] {"Nombre", "Cedula", "Edad", "Sexo", "Peso", "Altura", "Años de experiencia"}));
        TablaD.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {},new String [] {"Nombre", "Cedula", "Edad", "Sexo", "Peso", "Altura", "Ritmo Cardiaco", "Frecuencia de entrenamiento", "Tipo de ejercicios"}));
        control.LlenarTabla(datos, TablaE, TablaD, txtExpE, null, null, null);
        
    }//GEN-LAST:event_botonConsultaActionPerformed

    private void botonDeportistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeportistaActionPerformed
       control.activarPanel(panelDeportista, panelEntrenador, panelConsulta, panelUtilidades);
    }//GEN-LAST:event_botonDeportistaActionPerformed

    private void botonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseClicked
        int ax = JOptionPane.showConfirmDialog(null, "Estas seguro que deseas salir?",null, JOptionPane.YES_NO_OPTION);
        if(ax == JOptionPane.YES_OPTION){
        control.salirVentana(botonSalir);
        control.DetenerMusica();
        }
    }//GEN-LAST:event_botonSalirMouseClicked

    private void txtNombreEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEKeyTyped
      control.borrarCampo(txtNombreE,"Nombre:");
      control.ValidarLetras(evt);
    }//GEN-LAST:event_txtNombreEKeyTyped

    private void txtEdadEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadEKeyTyped
      control.borrarCampo(txtEdadE,"Edad:");
      control.ValidarEntero(evt);
    }//GEN-LAST:event_txtEdadEKeyTyped

    private void txtAlturaEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaEKeyTyped
      control.borrarCampo(txtAlturaE,"Altura:");
      control.ValidarDouble(evt);
    }//GEN-LAST:event_txtAlturaEKeyTyped

    private void txtPesoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoEKeyTyped
      control.borrarCampo(txtPesoE,"Peso:");
      control.ValidarDouble(evt);
    }//GEN-LAST:event_txtPesoEKeyTyped

    private void txtExpEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExpEKeyTyped
      control.borrarCampo(txtExpE,"Años de experiencia laboral:");
      control.ValidarEntero(evt);
    }//GEN-LAST:event_txtExpEKeyTyped

    private void txtNombreDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDKeyTyped
      control.borrarCampo(txtNombreD,"Nombre:");
      control.ValidarLetras(evt);
    }//GEN-LAST:event_txtNombreDKeyTyped

    private void txtEdadDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadDKeyTyped
      control.borrarCampo(txtEdadD,"Edad:");
      control.ValidarEntero(evt);
    }//GEN-LAST:event_txtEdadDKeyTyped

    private void txtAlturaDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaDKeyTyped
      control.borrarCampo(txtAlturaD,"Altura:");
      control.ValidarDouble(evt);
    }//GEN-LAST:event_txtAlturaDKeyTyped

    private void txtPesoDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoDKeyTyped
      control.borrarCampo(txtPesoD,"Peso:");
      control.ValidarDouble(evt);
    }//GEN-LAST:event_txtPesoDKeyTyped

    private void txtRitCarDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRitCarDKeyTyped
      control.borrarCampo(txtRitCarD,"Ritmo Cardiaco:");
      control.ValidarDouble(evt);
    }//GEN-LAST:event_txtRitCarDKeyTyped

    private void txtTipoEjerDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoEjerDKeyTyped
      control.borrarCampo(txtTipoEjerD,"Tipo de ejercicios:");
      control.ValidarLetras(evt);
    }//GEN-LAST:event_txtTipoEjerDKeyTyped

    private void txtFrecEntrDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrecEntrDKeyTyped
      control.borrarCampo(txtFrecEntrD,"Frecuencia de entrenamiento:");
      control.ValidarLetras(evt);
    }//GEN-LAST:event_txtFrecEntrDKeyTyped

    private void RegistrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEActionPerformed
      if(!txtNombreE.getText().equals("Nombre:") && !txtCelE.getText().equals("Cedula:") && !txtEdadE.getText().equals("Edad:") && !txtAlturaE.getText().equals("Altura:") && !txtPesoE.getText().equals("Peso:") && !txtExpE.getText().equals("Años de experiencia laboral:") && txtCelE.getText()!=null && txtNombreE.getText()!=null && txtPesoE.getText()!=null && txtAlturaE.getText()!=null && txtEdadE.getText()!=null && txtExpE.getText()!=null && txtEsp.getText()!=null && txtHoras.getText()!=null){
      TablaE.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {}, new String [] {"Nombre", "Cedula", "Edad", "Sexo", "Peso", "Altura", "Años de experiencia"}));
      TablaD.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {},new String [] {"Nombre", "Cedula", "Edad", "Sexo", "Peso", "Altura", "Ritmo Cardiaco", "Frecuencia de entrenamiento", "Tipo de ejercicios"}));
      Entrenador Entr = new Entrenador("Entrenador", Integer.parseInt(txtExpE.getText()), Integer.parseInt(txtCelE.getText()), txtNombreE.getText(), Integer.parseInt(txtEdadE.getText()), (String) boxSexoE.getSelectedItem(), Double.parseDouble(txtPesoE.getText()),Double.parseDouble(txtAlturaE.getText()), null);
      Entr.setEspecialidades(aux);
      resultado = datos.agregarPersona(Entr);
      control.LlenarTabla(datos, TablaE, TablaD, txtExpE, null, null, null);
      control.inicializarTxtE(txtNombreE, txtEdadE, txtAlturaE, txtPesoE, txtExpE, txtCelE, txtEsp, txtHoras);
      aux.clear();
      JOptionPane.showMessageDialog(this, "Entrenador registrado correctamente.");
      }
      else
      JOptionPane.showMessageDialog(this, "Por favor ingrese todos los datos requeridos.");
    }//GEN-LAST:event_RegistrarEActionPerformed

    private void RegistrarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarDActionPerformed
      if(!txtNombreD.getText().equals("Nombre:") && !txtCelD.getText().equals("Cedula:") && !txtEdadD.getText().equals("Edad:") && !txtAlturaD.getText().equals("Altura:") && !txtPesoD.getText().equals("Peso:") && !txtRitCarD.getText().equals("Ritmo Cardiaco:") && !txtTipoEjerD.getText().equals("Tipo de ejercicios:") && !txtFrecEntrD.getText().equals("Frecuencia de entrenamiento:") && txtCelD.getText()!=null && txtNombreD.getText()!=null && txtPesoD.getText()!=null && txtAlturaD.getText()!=null && txtEdadD.getText()!=null && txtRitCarD.getText()!=null && txtObj.getText()!=null && txtTipoEjerD.getText()!=null && txtEjer.getText()!=null && txtFrecEntrD.getText()!=null){
      TablaE.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {}, new String [] {"Nombre", "Cedula", "Edad", "Sexo", "Peso", "Altura", "Años de experiencia"}));
      TablaD.setModel(new javax.swing.table.DefaultTableModel(new Object [][] {},new String [] {"Nombre", "Cedula", "Edad", "Sexo", "Peso", "Altura", "Ritmo Cardiaco", "Frecuencia de entrenamiento", "Tipo de ejercicios"}));
      Deportista Depor = new Deportista("Deportista", Integer.parseInt(txtRitCarD.getText()), txtFrecEntrD.getText(), txtTipoEjerD.getText(), 0, Integer.parseInt(txtCelD.getText()), txtNombreD.getText(), Integer.parseInt(txtEdadD.getText()), (String) boxSexoD.getSelectedItem(), Double.parseDouble(txtPesoD.getText()),Double.parseDouble(txtAlturaD.getText()), null);
      Depor.setEjercicios(aux1);
      resultado = datos.agregarPersona(Depor);
      control.LlenarTabla(datos, TablaE, TablaD, null, txtRitCarD, txtFrecEntrD, txtTipoEjerD);
      control.inicializarTxtD(txtNombreD, txtEdadD, txtAlturaD, txtPesoD, txtRitCarD, txtTipoEjerD, txtEjer, txtObj, txtFrecEntrD, txtCelD);
      aux1.clear();
      JOptionPane.showMessageDialog(this, "Deportista registrado correctamente.");
      }
      else
      JOptionPane.showMessageDialog(this, "Por favor ingrese todos los datos requeridos.");    
    }//GEN-LAST:event_RegistrarDActionPerformed

    private void txtNombreEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreEFocusLost
      control.RestaurarTextfield(txtNombreE,"Nombre:");
    }//GEN-LAST:event_txtNombreEFocusLost

    private void txtEdadEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadEFocusLost
      control.RestaurarTextfield(txtEdadE,"Edad:");
    }//GEN-LAST:event_txtEdadEFocusLost

    private void txtAlturaEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlturaEFocusLost
      control.RestaurarTextfield(txtAlturaE,"Altura:");
    }//GEN-LAST:event_txtAlturaEFocusLost

    private void txtPesoEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesoEFocusLost
      control.RestaurarTextfield(txtPesoE,"Peso:");
    }//GEN-LAST:event_txtPesoEFocusLost

    private void txtExpEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtExpEFocusLost
      control.RestaurarTextfield(txtExpE,"Años de experiencia laboral:");
    }//GEN-LAST:event_txtExpEFocusLost

    private void txtNombreDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreDFocusLost
      control.RestaurarTextfield(txtNombreD,"Nombre:");
    }//GEN-LAST:event_txtNombreDFocusLost

    private void txtEdadDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadDFocusLost
      control.RestaurarTextfield(txtEdadD,"Edad:");
    }//GEN-LAST:event_txtEdadDFocusLost

    private void txtAlturaDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlturaDFocusLost
      control.RestaurarTextfield(txtAlturaD,"Altura:");
    }//GEN-LAST:event_txtAlturaDFocusLost

    private void txtPesoDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesoDFocusLost
      control.RestaurarTextfield(txtPesoD,"Peso:");
    }//GEN-LAST:event_txtPesoDFocusLost

    private void txtRitCarDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRitCarDFocusLost
      control.RestaurarTextfield(txtRitCarD,"Ritmo Cardiaco:");
    }//GEN-LAST:event_txtRitCarDFocusLost

    private void txtFrecEntrDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFrecEntrDFocusLost
      control.RestaurarTextfield(txtFrecEntrD,"Frecuencia de entrenamiento:");
    }//GEN-LAST:event_txtFrecEntrDFocusLost

    private void txtTipoEjerDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoEjerDFocusLost
      control.RestaurarTextfield(txtTipoEjerD,"Tipo de ejercicios:");
    }//GEN-LAST:event_txtTipoEjerDFocusLost

    private void IMCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMCDActionPerformed
      if(!txtNombreD.getText().equals("Nombre:") && !txtCelD.getText().equals("Cedula:") && !txtEdadD.getText().equals("Edad:") && !txtAlturaD.getText().equals("Altura:") && !txtPesoD.getText().equals("Peso:") && !txtRitCarD.getText().equals("Ritmo Cardiaco:") && !txtTipoEjerD.getText().equals("Tipo de ejercicios:") && !txtFrecEntrD.getText().equals("Frecuencia de entrenamiento:") && txtCelD.getText()!=null && txtNombreD.getText()!=null && txtPesoD.getText()!=null && txtAlturaD.getText()!=null && txtEdadD.getText()!=null && txtRitCarD.getText()!=null && txtObj.getText()!=null && txtTipoEjerD.getText()!=null && txtEjer.getText()!=null && txtFrecEntrD.getText()!=null){
      double IMC = control.calcularIMC(txtPesoD, txtAlturaD, txtEdadD, boxSexoD);
      double pgc = control.calcularPGC(txtPesoD, txtAlturaD, txtEdadD, boxSexoD);
      JOptionPane.showMessageDialog(this,"Su imc es: "+ IMC);
      JOptionPane.showMessageDialog(this,"Su PGC es: "+ pgc);
      String grasa = control.determinarGrasa(boxSexoD, pgc);
      JOptionPane.showMessageDialog(this,grasa);
      }
      else
      JOptionPane.showMessageDialog(this, "Por favor ingrese todos los datos requeridos antes de calcularlo.");  
    }//GEN-LAST:event_IMCDActionPerformed

    private void IMCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMCEActionPerformed
      if(!txtNombreE.getText().equals("Nombre:") && !txtCelE.getText().equals("Cedula:") && !txtEdadE.getText().equals("Edad:") && !txtAlturaE.getText().equals("Altura:") && !txtPesoE.getText().equals("Peso:") && !txtExpE.getText().equals("Años de experiencia laboral:") && txtCelE.getText()!=null && txtNombreE.getText()!=null && txtPesoE.getText()!=null && txtAlturaE.getText()!=null && txtEdadE.getText()!=null && txtExpE.getText()!=null && txtEsp.getText()!=null && txtHoras.getText()!=null){      
      double IMC = control.calcularIMC(txtPesoE, txtAlturaE, txtEdadE, boxSexoE);
      double pgc = control.calcularPGC(txtPesoE, txtAlturaE, txtEdadE, boxSexoE);
      String grasa = control.determinarGrasa(boxSexoE, pgc);
      JOptionPane.showMessageDialog(this,"Su IMC es: "+ IMC);
      JOptionPane.showMessageDialog(this,"Su PGC es: "+ pgc);
      JOptionPane.showMessageDialog(this,grasa);
      }
      else
      JOptionPane.showMessageDialog(this, "Por favor ingrese todos los datos requeridos antes de calcularlo.");    
    }//GEN-LAST:event_IMCEActionPerformed

    private void txtCelEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelEFocusLost
      control.RestaurarTextfield(txtCelE, "Cedula:");
    }//GEN-LAST:event_txtCelEFocusLost

    private void txtCelEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelEKeyTyped
      control.borrarCampo(txtCelE, "Cedula:");
      control.ValidarEntero(evt);
    }//GEN-LAST:event_txtCelEKeyTyped

    private void txtCelDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelDFocusLost
      control.RestaurarTextfield(txtCelD, "Cedula:");
    }//GEN-LAST:event_txtCelDFocusLost

    private void txtCelDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelDKeyTyped
      control.borrarCampo(txtCelD, "Cedula:");
      control.ValidarEntero(evt);
    }//GEN-LAST:event_txtCelDKeyTyped

    private void RutinaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutinaDActionPerformed
      if(!txtNombreD.getText().equals("Nombre:") && !txtCelD.getText().equals("Cedula:") && !txtEdadD.getText().equals("Edad:") && !txtAlturaD.getText().equals("Altura:") && !txtPesoD.getText().equals("Peso:") && !txtRitCarD.getText().equals("Ritmo Cardiaco:") && !txtTipoEjerD.getText().equals("Tipo de ejercicios:") && !txtFrecEntrD.getText().equals("Frecuencia de entrenamiento:") && txtCelD.getText()!=null && txtNombreD.getText()!=null && txtPesoD.getText()!=null && txtAlturaD.getText()!=null && txtEdadD.getText()!=null && txtRitCarD.getText()!=null && txtObj.getText()!=null && txtTipoEjerD.getText()!=null && txtEjer.getText()!=null && txtFrecEntrD.getText()!=null){
      double pgc = control.calcularPGC(txtPesoD, txtAlturaD, txtEdadD, boxSexoD);
      String rutina = control.determinarRutina(boxSexoD, pgc);
      JOptionPane.showMessageDialog(this,rutina);
      }
      else
      JOptionPane.showMessageDialog(this, "Por favor ingrese todos los datos requeridos antes de determinar la rutina.");
    }//GEN-LAST:event_RutinaDActionPerformed

    private void ListaEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaEspActionPerformed
       if(!txtEsp.getText().equals("Especialidad:") && !txtHoras.getText().equals("Horas dictadas:") && txtEsp.getText()!=null && txtHoras.getText()!=null ){
       Especialidad esp = new Especialidad(txtEsp.getText(), Integer.parseInt(txtHoras.getText()));
       control.LlenarListaA(esp, aux);
       txtEsp.setText("Especialidad:");
       txtHoras.setText("Horas dictadas:");
       JOptionPane.showMessageDialog(this, "Especialidad almacenada correctamente.");
       }
       else
       JOptionPane.showMessageDialog(this, "Por favor ingrese los datos necesarios para registrar la especialidad.");       
    }//GEN-LAST:event_ListaEspActionPerformed

    private void RegistrarEjerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEjerActionPerformed
        if(!txtEjer.getText().equals("Nombre del ejercicio:") && !txtObj.getText().equals("Horas dictadas:") && txtEjer.getText()!=null && txtObj.getText()!=null ){
        Ejercicio eje = new Ejercicio (txtEjer.getText(),txtObj.getText());
        control.LlenarListaA1(eje, aux1);
        txtEjer.setText("Nombre del ejercicio:");
        txtObj.setText("Objetivo del ejercicio:");
        JOptionPane.showMessageDialog(this, "Ejercicio almacenado correctamente.");
        }
        else
        JOptionPane.showMessageDialog(this, "Por favor ingrese los datos necesarios para registrar el ejercicio.");
    }//GEN-LAST:event_RegistrarEjerActionPerformed

    private void txtEjerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEjerFocusLost
        control.RestaurarTextfield(txtEjer, "Nombre del ejercicio:");
    }//GEN-LAST:event_txtEjerFocusLost

    private void txtEjerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEjerKeyTyped
        control.borrarCampo(txtEjer, "Nombre del ejercicio:");
        control.ValidarLetras(evt);
    }//GEN-LAST:event_txtEjerKeyTyped

    private void txtObjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObjFocusLost
        control.RestaurarTextfield(txtObj, "Objetivo del ejercicio:");
    }//GEN-LAST:event_txtObjFocusLost

    private void txtObjKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObjKeyTyped
      control.borrarCampo(txtObj, "Objetivo del ejercicio:");
      control.ValidarLetras(evt);
    }//GEN-LAST:event_txtObjKeyTyped

    private void txtEspFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEspFocusLost
        control.RestaurarTextfield(txtEsp, "Especialidad:");
    }//GEN-LAST:event_txtEspFocusLost

    private void txtEspKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspKeyTyped
      control.borrarCampo(txtEsp, "Especialidad:");
      control.ValidarLetras(evt);
    }//GEN-LAST:event_txtEspKeyTyped

    private void txtHorasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHorasFocusLost
        control.RestaurarTextfield(txtHoras, "Horas dictadas:");
    }//GEN-LAST:event_txtHorasFocusLost

    private void txtHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHorasKeyTyped
      control.borrarCampo(txtHoras, "Horas dictadas:");
      control.ValidarEntero(evt);
    }//GEN-LAST:event_txtHorasKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      control.activarPanel(panelUtilidades, panelConsulta, panelEntrenador, panelDeportista);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GuardarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarEActionPerformed
      control.salvarPersonaE(datos, txtNombreE, txtEdadE, txtAlturaE, txtPesoE, txtExpE, txtCelE, txtEsp, txtHoras);
      control.inicializarTxtE(txtNombreE, txtEdadE, txtAlturaE, txtPesoE, txtExpE, txtCelE, txtEsp, txtHoras);
      control.activar_desactivarE(true, RegistrarE);
      control.activar_desactivarE(false, GuardarE);
    }//GEN-LAST:event_GuardarEActionPerformed

    private void GuardarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDActionPerformed
      control.salvarPersonaD(datos, txtNombreD, txtEdadD, txtAlturaD, txtPesoD, txtRitCarD, txtTipoEjerD, txtEjer, txtObj, txtFrecEntrD, txtCelD);
      control.inicializarTxtD(txtNombreD, txtEdadD, txtAlturaD, txtPesoD, txtRitCarD, txtTipoEjerD, txtEjer, txtObj, txtFrecEntrD, txtCelD);
      control.activar_desactivarD(true, RegistrarD);
      control.activar_desactivarD(false, GuardarD);
    }//GEN-LAST:event_GuardarDActionPerformed

    private void modificarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarDActionPerformed
        JOptionPane.showMessageDialog(this, "Proximamente. En construcción.");
    /*  if(!txtCelel.getText().equals("Buscar cedula:") && txtCelel.getText()!=null){
            control.activar_desactivarD(true, GuardarD);
            control.modificarDeportista(datos, txtCelel, panelDeportista, panelEntrenador, panelConsulta, panelUtilidades, txtNombreD, txtEdadD, txtAlturaD, txtPesoD, txtRitCarD, txtTipoEjerD, txtEjer, txtObj, txtFrecEntrD, txtCelD, RegistrarD, GuardarD);
            txtCelel.setText("Buscar cedula:");
        }
        else
        JOptionPane.showMessageDialog(this, "Por favor ingrese una cédula válida."); */
    }//GEN-LAST:event_modificarDActionPerformed

    private void ejerFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejerFavActionPerformed
        JOptionPane.showMessageDialog(this, "Proximamente. En construcción.");
    }//GEN-LAST:event_ejerFavActionPerformed

    private void mostrarEjerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEjerActionPerformed
        JOptionPane.showMessageDialog(this, "Proximamente. En construcción.");
    }//GEN-LAST:event_mostrarEjerActionPerformed

    private void mostrarEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEspActionPerformed
        JOptionPane.showMessageDialog(this, "Proximamente. En construcción.");
    }//GEN-LAST:event_mostrarEspActionPerformed

    private void modificarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEActionPerformed
        JOptionPane.showMessageDialog(this, "Proximamente. En construcción.");
        /*if(!txtCelel.getText().equals("Buscar cedula:") && txtCelel.getText()!=null){
            control.activar_desactivarE(true, GuardarE);
            control.modificarEntrenador(datos, txtCelel, panelEntrenador, panelDeportista, panelConsulta, panelUtilidades, txtNombreE, txtEdadE, txtAlturaE, txtPesoE, txtExpE, txtCelE, txtEsp, txtHoras, RegistrarE, GuardarE);
            txtCelel.setText("Buscar cedula:");
        }
        else
        JOptionPane.showMessageDialog(this, "Por favor ingrese una cédula válida."); */
    }//GEN-LAST:event_modificarEActionPerformed

    private void txtCelelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelelKeyTyped
        control.borrarCampo(txtCelel, "Buscar cedula:");
        control.ValidarEntero(evt);
    }//GEN-LAST:event_txtCelelKeyTyped

    private void txtCelelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelelFocusLost
        control.RestaurarTextfield(txtCelel, "Buscar cedula:");
    }//GEN-LAST:event_txtCelelFocusLost

    private void eliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPActionPerformed
        if(!txtCelel.getText().equals("Buscar cedula:") && txtCelel.getText()!=null){
            control.eliminarPersona(datos, txtCelel);
            txtCelel.setText("Buscar cedula:");
            JOptionPane.showMessageDialog(this, "Se ha eliminado correctamente.");
        }
        else
        JOptionPane.showMessageDialog(this, "Por favor ingrese una cédula válida.");
    }//GEN-LAST:event_eliminarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarD;
    private javax.swing.JButton GuardarE;
    private javax.swing.JButton IMCD;
    private javax.swing.JButton IMCE;
    private javax.swing.JButton ListaEsp;
    private javax.swing.JPanel PanelBotton;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JButton RegistrarD;
    private javax.swing.JButton RegistrarE;
    private javax.swing.JButton RegistrarEjer;
    private javax.swing.JButton RutinaD;
    private javax.swing.JTable TablaD;
    private javax.swing.JTable TablaE;
    private javax.swing.JButton botonConsulta;
    private javax.swing.JButton botonDeportista;
    private javax.swing.JButton botonEntrenador;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox boxSexoD;
    private javax.swing.JComboBox boxSexoE;
    private javax.swing.JButton ejerFav;
    private javax.swing.JButton eliminarP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton modificarD;
    private javax.swing.JButton modificarE;
    private javax.swing.JButton mostrarEjer;
    private javax.swing.JButton mostrarEsp;
    private javax.swing.JLayeredPane panelCentral;
    private javax.swing.JPanel panelConsulta;
    private javax.swing.JPanel panelDeportista;
    private javax.swing.JPanel panelEntrenador;
    private javax.swing.JPanel panelUtilidades;
    private javax.swing.JTextField txtAlturaD;
    private javax.swing.JTextField txtAlturaE;
    private javax.swing.JTextField txtCelD;
    private javax.swing.JTextField txtCelE;
    private javax.swing.JTextField txtCelel;
    private javax.swing.JTextField txtEdadD;
    private javax.swing.JTextField txtEdadE;
    private javax.swing.JTextField txtEjer;
    private javax.swing.JTextField txtEsp;
    private javax.swing.JTextField txtExpE;
    private javax.swing.JTextField txtFrecEntrD;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtNombreD;
    private javax.swing.JTextField txtNombreE;
    private javax.swing.JTextField txtObj;
    private javax.swing.JTextField txtPesoD;
    private javax.swing.JTextField txtPesoE;
    private javax.swing.JTextField txtRitCarD;
    private javax.swing.JTextField txtTipoEjerD;
    // End of variables declaration//GEN-END:variables
}
